name: fesl-cpu
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py38h06a4308_0
  - intel-openmp=2020.2=254
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - mpmath=1.1.0=py38_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - openssl=1.1.1i=h27cfd23_0
  - pip=20.3.3=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.1=h27cfd23_0
  - scipy=1.6.0=py38h91f5cce_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - alembic==1.5.4
    - ase==3.21.1
    - attrs==20.3.0
    - cliff==3.7.0
    - cmaes==0.8.1
    - cmd2==1.5.0
    - colorama==0.4.4
    - colorlog==4.7.2
    - cycler==0.10.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - mako==1.1.4
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - oapackage==2.6.8
    - optuna==2.5.0
    - packaging==20.9
    - pbr==5.5.1
    - pillow==8.1.0
    - prettytable==2.0.0
    - pyparsing==2.4.7
    - pyperclip==1.8.1
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pyyaml==5.4.1
    - sqlalchemy==1.3.23
    - stevedore==3.3.0
    - torch==1.7.1+cpu
    - torchaudio==0.7.2
    - torchvision==0.8.2+cpu
    - tqdm==4.57.0
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5

