name: mala-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py38h497a2fe_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alembic=1.7.6=pyhd8ed1ab_0
  - ase=3.22.1=pyhd8ed1ab_1
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - autopage=0.5.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py38h497a2fe_1003
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.3=py38h578d9bd_1
  - cliff=3.10.0=pyhd8ed1ab_0
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=2.3.3=py38h578d9bd_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=6.6.0=py38h578d9bd_0
  - cryptography=36.0.1=py38h3e25421_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - flask=2.0.3=pyhd8ed1ab_0
  - fonttools=4.29.1=py38h497a2fe_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.0=py38h497a2fe_0
  - future=0.18.2=py38h578d9bd_4
  - giflib=5.2.1=h36c2ea0_2
  - google-auth=2.6.0=pyh6c4a22f_1
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - greenlet=1.1.2=py38h709712a_1
  - grpcio=1.43.0=py38hdd6454d_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.0=py38h578d9bd_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - kiwisolver=1.3.2=py38h1fd1430_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_mkl
  - libdeflate=1.10=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libimagequant=2.17.0=h7f98852_1
  - liblapack=3.9.0=13_linux64_mkl
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.4=h780b84a_0
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h542a066_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=13.0.1=hf817b99_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mako=1.1.6=pyhd8ed1ab_0
  - markdown=3.3.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h497a2fe_1
  - matplotlib-base=3.5.1=py38hf4fb855_0
  - mkl=2022.0.1=h8d4b97c_803
  - mpmath=1.2.1=pyhd8ed1ab_0
  - multidict=6.0.2=py38h497a2fe_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h9c3ff4c_0
  - ninja=1.10.2=h4bd325d_1
  - numpy=1.22.2=py38h6ae9a64_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openpmd-api=0.14.5=py310hb1c60db_3
  - openssl=1.1.1l=h7f98852_0
  - optuna=2.10.0=pyhd8ed1ab_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py38h43a58ef_0
  - pbr=5.8.1=pyhd8ed1ab_0
  - pillow=9.0.1=py38he2f12e7_1
  - pip=22.0.3=pyhd8ed1ab_0
  - prettytable=3.1.0=pyhd8ed1ab_0
  - protobuf=3.19.4=py38h709712a_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pysocks=1.7.1=py38h578d9bd_4
  - python=3.8.12=ha38a3c6_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.2=cpu_py38hb2150b6_0
  - pytorch-cpu=1.10.2=cpu_py38h718b53a_0
  - pytz=2021.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h497a2fe_3
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - scipy=1.8.0=py38h56a6a73_1
  - setuptools=59.5.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sqlalchemy=1.4.31=py38h497a2fe_0
  - sqlite=3.37.0=h9cd32fc_0
  - stevedore=3.5.0=py38h578d9bd_2
  - tbb=2021.5.0=h4bd325d_0
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py38h3e25421_1
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - unicodedata2=14.0.0=py38h497a2fe_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.3=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h497a2fe_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
