name: mala-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alembic=1.6.5=pyhd8ed1ab_0
  - ase=3.21.1=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.5=py38ha65f79e_0
  - click=8.0.1=py38h578d9bd_0
  - cliff=3.8.0=pyhd8ed1ab_0
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=2.0.1=py38h578d9bd_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=5.0.1=py38h578d9bd_0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_1
  - flask=2.0.1=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py38h578d9bd_3
  - greenlet=1.1.0=py38h709712a_0
  - importlib-metadata=4.5.0=py38h578d9bd_0
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - liblapack=3.9.0=8_mkl
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.3.0=hf544144_1
  - libwebp-base=1.2.0=h7f98852_2
  - llvm-openmp=11.1.0=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_0
  - mako=1.1.4=pyh44b312d_0
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-base=3.4.2=py38hcc49a3a_0
  - mkl=2020.4=h726a3e6_304
  - mpmath=1.2.1=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.20.3=py38h9894fe3_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - optuna=2.8.0=pyhd8ed1ab_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py38h1abd341_0
  - pbr=5.6.0=pyhd8ed1ab_0
  - pillow=8.2.0=py38ha0e1e83_1
  - pip=21.1.2=pyhd8ed1ab_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.9.0=cpu_py38h4bbe6ce_2
  - pytorch-cpu=1.9.0=cpu_py38h718b53a_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - readline=8.1=h46c0cb4_0
  - scipy=1.6.3=py38h7b17777_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h7f98852_1
  - sqlalchemy=1.4.18=py38h497a2fe_0
  - sqlite=3.35.5=h74cdb3f_0
  - stevedore=3.3.0=py38h578d9bd_1
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.61.1=pyhd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
