name: mala-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - numpy
  - scipy
  - optuna
  - pandas
  - ase
  - pytorch-cpu<2.6.0
  - mpmath
  - tensorboard
  - scikit-spatial
  - mendeleev
  - sympy
  - pip:
      - openpmd-api
